version: '2'

services:

    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: urbndag
        environment:
            - DB_HOST=db
        ports:
            - '8002:8002'
        volumes:
            - ./source/:/usr/src/app/
        command: npm run start